name: Build and Push Docker Image

# Trigger on pushes to the main branch (adjust as needed)
on:
  push:
    branches: ["master"]

jobs:
  build_and_push:
    # Run on an Ubuntu virtual machine
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Log in to Docker Hub (or another registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build the Docker image (adjust image name to your registry/repo)
      - name: Build Docker Image
        run: |
          docker build -t casualcomputer/install-github-app:latest .

      # Push the Docker image
      - name: Push Docker Image
        run: |
          docker push casualcomputer/install-github-app:latest
